# Use a lightweight base image for PostgreSQL
FROM postgres:alpine

# Set environment variables for PostgreSQL
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=123
ENV POSTGRES_DB=PackageTracking_db

# Expose the PostgreSQL port
EXPOSE 5432
